# version: "3.9"

services:
  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./next:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - shared-network

  app:
    build:
      context: ./express
      dockerfile: Dockerfile
    tty: true
    ports:
      - '4000:4000'
      - '9229:9229'
    volumes:
      - ./express:/usr/src/app
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/mydatabase
    depends_on:
      - db
    networks:
      - shared-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - shared-network

volumes:
  mysqldata:

networks:
  shared-network:
    driver: bridge
