@startuml app
entity "Users" {
  *id : integer
  --
  member : string
  name : string
  mail : string
}

entity "income_and_expenditure" {
  *id : integer
  --
  category_id : integer <<FK>>
  user_id : integer <<FK>>
  transaction_id : integer <<FK>>
  payment_type : string
  day : date
  amount : integer
}

entity "category" {
  *id : integer
  --
  contents : string
}

entity "payment" {
  *id : integer
  --
  user_id : integer <<FK>>
  payment_items : string
}

entity "transaction" {
  *id : integer
  --
  user_id : integer <<FK>>
  category_id : integer <<FK>>
  payment_id : integer <<FK>>
  member : string
  name : string
  payment_items : string
  payment_type : string
  day : date
  amount : integer
  contents : string
  remarks : string
}

Users ||--o{ income_and_expenditure : has
Users ||--o{ payment : has
Users ||--o{ transaction : makes

income_and_expenditure }o--|| category : belongs to
income_and_expenditure ||--|| transaction : is part of

transaction }o--|| category : belongs to
transaction }o--|| payment : uses
@enduml